spring:
  application:
    name: firstboot
  config:
    activate:
      on-profile: prod
# ---- Server Configs ----
server:
  port: ${MY_PORT:9090}
# ---- Aplication configs ----
blandygbc:
  firstboot:
    buildNumber: 1.1-alpha

---
spring:
  application:
    name: firstboot
# ---- Profile ----
  config:
    activate:
      on-profile: dev
# ---- Database ----
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/firstboot
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
# ---- Liquibase ----
  liquibase:
    enabled: true
    change-log: db/changelog/log.xml
# ---- Server Configs ----
server:
  port: ${MY_PORT:8080}

# ---- Aplication configs ----
blandygbc:
  firstboot:
    buildNumber: 1.5-dev
logging:
  level:
    com:
      blandygbc:
        firstboot:
          LogginController: TRACE